name: Dev Build and Store Artifact

on:
  push:
    branches:
      - dev # Auto-run build when pushing to dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build the Project
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/ # Stores the Next.js build
