name: Artifact-Based Deployment to Netlify

on:
  push:
    branches:
      - dev # Runs when code is pushed to dev
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build the Project
        run: yarn build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next/ # Stores the Next.js build folder

  manual-approval:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Await Manual Approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          approve-label: "Ready for Promotion"

  promote:
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        run: |
          git fetch origin main
          git checkout main
          git merge dev --no-ff -m "Promoting dev to main"
          git push origin main

  deploy:
    needs: promote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main # Ensures deployment is from the main branch

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .next/ # Uses the same build artifact

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --dir=.next --prod --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
