name: Promote to Production

on:
  workflow_dispatch: # Runs ONLY when manually triggered

jobs:
  promote-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4

      - name: Merge Dev into Main
        run: |
          git fetch origin
          git checkout main
          git merge dev --no-ff -m "Promote dev to main"
          git push origin main
